import type { Client, Package } from '@/types/database';

export const CONTRACT_STATUSES = ['rascunho', 'gerado', 'enviado', 'assinado', 'cancelado'] as const;
export type ContractStatus = (typeof CONTRACT_STATUSES)[number];

export type ContractRecord = {
  id: string;
  company_id: string;
  event_id: string | null;
  client_id: string | null;
  package_id: string | null;
  contract_number: number;
  contract_year: number;
  status: ContractStatus;
  contractor_name: string;
  contractor_document: string | null;
  contractor_rg: string | null;
  contractor_address: string | null;
  contractor_phone: string | null;
  contractor_email: string | null;
  children_estimate: number | null;
  event_date: string | null;
  start_time: string | null;
  end_time: string | null;
  event_location: string | null;
  event_location_type: string | null;
  team_size: number;
  included_activities: string[];
  included_equipment: string[];
  total_amount: number;
  displacement_amount: number;
  deposit_amount: number;
  deposit_date: string | null;
  balance_amount: number;
  balance_due_date: string | null;
  payment_method: string | null;
  pix_key: string | null;
  additional_payment_terms: string | null;
  catering_required: boolean;
  image_authorized: boolean;
  additional_observations: string | null;
  contract_details: string | null;
  generated_text: string | null;
  created_at: string;
  updated_at: string;
  client?: Client | null;
  package?: Package | null;
};